version: "3.9"

services:
  nextjs-dev:
    container_name: nextjs_dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  nextjs-prod:
    container_name: nextjs_prod
    build:
      context: .
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production